### ISSUE TITLE
micro sd

### ISSUE THREAD

**Issue by Frennic** [stooged/Pico-Server-900#3]
Is it possible to add micro sd support? Wiring a sd is simple and cheap with these pico boards. 6 wires to a micro sd to sd adapter and done.

Diagram 
https://leanpub.com/site_images1/rpitandt/sdcard-connection-ghetto.png

https://github.com/micropython/micropython-lib/blob/master/micropython/drivers/storage/sdcard/sdcard.py

Since pi 4 and zero are unobtanium, $9 total for pico w and sd card w adapter is pretty cheap.

**Comment by stooged** [comment]
added sd support
