### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by neo305** [stooged/Pico-Server-900#4]
what should the settings be?
![image_2023-01-24_23-31-46](https://user-images.githubusercontent.com/25275928/214480497-05569fb4-cfab-40fd-993a-73b9a473965b.png)

**Comment by neo305** [comment]
and how do I get the port to open? there is only 1 button on this thing and all I can get it to do is open a G Drive with 2 files on it, index.html and info.txt

**Comment by stooged** [comment]
Hold the button down when you plug it in and it will go into bootloader mode so arduino can upload the uf2.

**Comment by neo305** [comment]
that's what I did and it just opens up a G Drive on PC with the 2 files on it and has 127mb lol nice

**Comment by neo305** [comment]
and I look in Disk Management and it only sho
![image_2023-01-25_00-18-34](https://user-images.githubusercontent.com/25275928/214486121-7cf67927-907f-4ceb-b110-77ff8b1acd61.png)
ws up in disk drives

**Comment by neo305** [comment]
Ok installing pico setup windows.exe now lol

**Comment by neo305** [comment]
Please tell me this thing has more than a 2mb flash size :(

**Comment by stooged** [comment]
It only has 2mb with a maximum of 1mb for storage via littlefs

**Comment by neo305** [comment]
Holy crap that sux monkey balls. Can it at least use USBMSC like S2? The adafruit tinyusb?

**Comment by stooged** [comment]
Yes the tinyusb library has been ported 
https://github.com/earlephilhower/arduino-pico/tree/master/libraries

**Comment by neo305** [comment]
ok I got this far. what do I do after upload? cuz there was no files on it and wouldn't let me upload any files via manager.
![image_2023-01-25_01-07-33](https://user-images.githubusercontent.com/25275928/214493514-60a7ef77-9cd0-49ee-a816-8c5715cd1ba2.png)

**Comment by stooged** [comment]
You need to select the partition size in arduino.
1mb app/ 1mb fs

Then you should see 1mb in the total space.

**Comment by stooged** [comment]
![Uploading 20230125_142321.jpg…]()

**Comment by stooged** [comment]
<img src="https://i.ibb.co/DkT62X0/20230125-142321.jpg">

**Comment by neo305** [comment]
> Yes the tinyusb library has been ported https://github.com/earlephilhower/arduino-pico/tree/master/libraries

where do i put the folder?
![image_2023-01-25_01-31-56](https://user-images.githubusercontent.com/25275928/214496426-a46e3d78-a070-49fc-a7dc-50fc7a93f5c6.png)
![image_2023-01-25_01-32-34](https://user-images.githubusercontent.com/25275928/214496486-8595d074-5b42-408c-b408-97d292d8b814.png)

**Comment by neo305** [comment]
after upload I get this, then what? cuz nothing is on the board again
Sketch uses 440436 bytes (42%) of program storage space. Maximum is 1044480 bytes.
Global variables use 72296 bytes (27%) of dynamic memory, leaving 189848 bytes for local variables. Maximum is 262144 bytes.
C:\Users\Laz\AppData\Local\Arduino15\packages\rp2040\tools\pqt-python3\1.0.1-base-3a57aed/python3 -I C:\Users\Laz\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.7.1/tools/uf2conv.py --serial UF2_Board --family RP2040 --deploy C:\Users\Laz\AppData\Local\Temp\arduino_build_776085/Pico_Server_900.ino.uf2 
Converting to uf2, output size: 914432, start address: 0x2000
Flashing G: (RPI-RP2)
Wrote 914432 bytes to G:/NEW.UF2

**Comment by neo305** [comment]
I’m tired. Off to bed. Thanks c ya tomorrow

**Comment by neo305** [comment]
Ok nm about adafruit folder. I see it’s already there

**Comment by stooged** [comment]
it looks like it wrote the uf2 to the board so it should be up and running, if you are looking to upload html to the board use the file manager in the admin panel or use the upload tool for arduino.

https://github.com/earlephilhower/arduino-pico-littlefs-plugin

remember the pico on has 2mb flash with 1mb available for the storage, if you want more storage on the pico then you would need to use the sd card option.

https://github.com/stooged/Pico-Server-900/tree/main/sd
