### ISSUE TITLE
add second USB Port?

### ISSUE THREAD

**Issue by fhu123** [stooged/Pico-Server-900#5]
Hi,
at first thx for sharing your great work!!!!!. Works like a charm, but i have some questions about to add some features.
I want to activate Goldhen and after that i wish to share my USB Port with the PI for downloading PKS´s and install it to USB to PS4 without Disconnect to PS4. 
Is that possible to implement this with an additional USB Port?

Tia
Frank

**Comment by stooged** [comment]
The pico does not have usb3 so attemping to go through it would be extremely slow.

The easiest way to add more usb ports is to use one of the dobe hubs

Phat
http://www.dobe-game.com/en/productshow-55-151.html

Slim
http://www.dobe-game.com/en/productshow-54-167.html

Pro
http://www.dobe-game.com/en/productshow-53-177.html

**Comment by fhu123** [comment]
OK, i will try this ...

https://www.virtualhere.com/usb_server_software

think that´s the way USB remote
